// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-aetW_9Ivin8OzttjnpjFP90TF1JE1lQ',
    appId: '1:800552348818:web:f01ac0d5f85e2d74ab0a4b',
    messagingSenderId: '800552348818',
    projectId: 'fir-tutorial-42c26',
    authDomain: 'fir-tutorial-42c26.firebaseapp.com',
    storageBucket: 'fir-tutorial-42c26.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA67zAOelcNuNiosRotM0gX1jOdDEEmw-E',
    appId: '1:800552348818:android:0ac76614601822eeab0a4b',
    messagingSenderId: '800552348818',
    projectId: 'fir-tutorial-42c26',
    storageBucket: 'fir-tutorial-42c26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1pnOptkYagMq2SoRAtuU3QdjnozaWJm4',
    appId: '1:800552348818:ios:d6bdf0e0e1086ba4ab0a4b',
    messagingSenderId: '800552348818',
    projectId: 'fir-tutorial-42c26',
    storageBucket: 'fir-tutorial-42c26.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTutor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1pnOptkYagMq2SoRAtuU3QdjnozaWJm4',
    appId: '1:800552348818:ios:d6bdf0e0e1086ba4ab0a4b',
    messagingSenderId: '800552348818',
    projectId: 'fir-tutorial-42c26',
    storageBucket: 'fir-tutorial-42c26.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTutor',
  );
}
